# simple.gocd.yaml
pipelines:
  Test.Android:
    group: Test
    label_template: "${COUNT}"
    locking: on
    materials:
      mygit:  # this is the name of material
        # says about type of material and url at once
        git: https://github.com/tallnato/test-go-cd-plugin.git
        branch: master
    stages:
      - setupstage: # name of stage
        fetch_materials: yes
        keep_artifacts: no
        clean_workspace: yes
        jobs:
          setupjob: # name of the job
            timeout: 15
            run_instances: 1
            tasks:
             - exec: # indicates type of task
                 script: ./hello_world.sh
